version: '3.4'

services:
  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  q1-2022-apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}q12022apigateway
    ports:
        - "5000:80"

    build:
      context: .
      dockerfile: Q1-2022-ApiGateway/Dockerfile
    
  test:
    container_name: test
    image: ${DOCKER_REGISTRY-}test
    ports:
        - "5001:80"

    build:
      context: .
      dockerfile: test/Dockerfile
  
  SurveyService:
    container_name: survey_service
    image: ${DOCKER_REGISTRY-}q12022expresssurveyservice
    ports:
        - "5002:80"
    environment:
        - PORT=80
        - DATABASE_URL=mongodb://root:rootpassword@mongodb:27017/


    build:
      context: ../../Q1-2022-Express-Survey-Service/
      dockerfile: Dockerfile
