name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies # Get used packages
      run: dotnet restore "/Q1-2022-ApiGateway/Q1-2022-ApiGateway.csproj"
    - name: Build # Build main project
      run: dotnet build --no-restore  "/Q1-2022-ApiGateway/Q1-2022-ApiGateway.csproj"
    - name: Test # Run tests
      run: dotnet test --no-build --verbosity normal ./test/test.csproj
