name: deploy-appengine Integration

on:
  push:
    branches:
    - 'Dev'
  pull_request:

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/deploy-appengine@v0'
    
    - id: deploy
     name: 'Deploy to App Engine'
     uses: 'google-github-actions/deploy-appengine@v0'
     with:
      deliverables: 'app.yaml'
      project_id: ${{ secrets.GCP_PROJECT }}
      service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      promote: false
      version: 'v1'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'