name: Deploy to Google App Engine
on:
  push:
    branches:
      - Dev
jobs:
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: Build image
        working-directory: ./Q1-2022-ApiGateway
        run: gcloud builds submit --region=europe-west1 --config cloudbuild.yaml
      - name: 'Deploy to App Engine'
        run: |
           gcloud app deploy app.yaml --image-url europe-west1-docker.pkg.dev/dinner-in-motion-project/docker-repo-dinner-in-motion/image --project dinner-in-motion-project
           gcloud app browse --project=dinner-in-motion-project
        shell: bash
        


