
name: Deploy to Google App Engine
on:
  push:
    branches:
      - Dev
jobs:
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml
          project_id: '${{ secrets.GCP_PROJECT}}'
          credentials: ${{ secrets.GCP_CREDENTIALS }}