--- 
jobs: 
  deploy: 
    name: "Deploying to Google Cloud"
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        id: deploy
        name: "Deploy to App Engine"
        uses: google-github-actions/deploy-appengine@v0.2.0
        with: 
          deliverables: app.yaml
          image_url: gcr.io/dinner-in-motion-project/gatewayapi
          project_id: "${{ secrets.GCP_PROJECT }}"
      - 
        name: Test
        run: "curl \"${{ steps.deploy.outputs.url }}\""
name: "Deploy to GAE"
true: 
  pull_request: 
    branches: 
      - Dev
  push: 
    branches: 
      - Dev
  workflow_dispatch: ~
