name: deploy-appengine Integration

on:
  push:
    branches:
    - 'Dev'
  pull_request:

jobs:
  deploy_to_GAE
   
  steps:
    - id: 'auth'
      uses: 'google-github-actions/deploy-appengine@v0'
    
    - id: deploy
     name: 'Deploy to App Engine'
     uses: 'google-github-actions/deploy-appengine@v0'
     with:
      deliverables: 'app.yaml'
      project_id: ${{ secrets.GCP_PROJECT }}
      service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      version: 'v1'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'