
name: Deploy to Google App Engine
on:
  push:
    branches:
      - Dev
jobs:
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml
          project_id: '${{ secrets.GCP_PROJECT}}'
          