name: Deploy to Google App Engine
on:
  push:
    branches:
      - Dev
jobs:
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: 'Deploy to App Engine'
        run: |
           gcloud builds submit "\Q1-2022-ApiGateway" --tag gcr.io/dinner-in-motion-project/gatewayapi --project dinner-in-motion-project
           gcloud app deploy \Q1-2022-ApiGateway\bin\Release\net6.0\publish\app.yaml --image-url gcr.io/dinner-in-motion-project/gatewayapi --project dinner-in-motion-project
           gcloud app browse --project=dinner-in-motion-project
        shell: bash
        
#uses: 'google-github-actions/deploy-appengine@v0'
        #with:
          #deliverables: 'app.yaml'
          #image-url: gcr.io/dinner-in-motion-project/gatewayapi
          #promote: false
          #version: 'v1'

